import os
from pathlib import Path
from typing import Dict, List

from _common import config
from _common import props
from bs4 import BeautifulSoup, Tag
from svg.path import parse_path, Close, Move

INPUT_FOLDER = Path('final_outlines')


class Main:
	sets_data: List
	prop_names: Dict
	soup: BeautifulSoup
	root: Tag
	
	def __init__(self):
		self.sets_data = [[] for _ in range(6)]
		self.prop_names = dict()
		
		for svg_file in INPUT_FOLDER.iterdir():
			# print(svg_file)
			with svg_file.open('r', encoding='utf-8') as f:
				self.soup = BeautifulSoup(f.read(), 'xml')
			
			self.root = self.soup.svg
			
			prop_elements = self.root.find_all('g')
			
			for prop_element in prop_elements:
				# print(prop_element['id'])
				prop_set, prop_group, prop_index = map(int, prop_element['id'].split('_')[1:])
				
				path_elements = prop_element.find_all('path')
				rect_element = prop_element.rect
				prop_key = (prop_set, prop_group, prop_index)
				self.prop_names[prop_key] = f'{prop_set}.{prop_group}.{prop_index} - {prop_element.title.string.strip()}'
				
				if len(path_elements) == 0:
					continue
					
				offset_x, offset_y = float(rect_element['x'] if rect_element.has_attr('x') else 0), float(rect_element['y'] if rect_element.has_attr('y') else 0)
				# print(offset_x, offset_y)
				
				groups_data = self.sets_data[prop_set - 1]
				if len(groups_data) <= prop_group:
					for i in range(len(groups_data), prop_group + 1):
						groups_data.append([])
				
				props_data = groups_data[prop_group]
				
				if len(props_data) < prop_index:
					for i in range(len(props_data), prop_index):
						props_data.append('')
				
				# print(prop_set, prop_group, prop_index)
				# path_components = [f'{offset_x},{offset_y}']
				path_components = []
				
				for path_element in path_elements:
					path_data = parse_path(path_element['d'])
					component_start_index = -1
					path_output = []
					
					for path_item in path_data:
						if isinstance(path_item, Close):
							continue
						
						if isinstance(path_item, Move):
							if component_start_index != -1:
								path_output.append('},{')
							component_start_index = len(path_output)
						
						x, y = path_item.end.real, path_item.end.imag
						path_output.append(x + offset_x - 1)
						path_output.append(y + offset_y - 1)
					
					path_components.append(','.join(map(str, path_output)))
				
				props_data[prop_index - 1] = '{' + ','.join(path_components).replace(',},{,', '},{') + '}'
				pass
		
		output_file = config.LIB / 'props/outlines.cpp'
		output_file.parent.mkdir(parents=True, exist_ok=True)
		
		with output_file.open('w') as outfile:
			outfile.write('/// Auto generated by .scripts/prop_outline_generator/. Do not edit.\n\n')
			outfile.write(f'const array<array<array<array<array<float>>>>> PROP_OUTLINES = {{\n')
			for set_index, set_list in enumerate(self.sets_data):
				outfile.write(f'\t{{ // Set {set_index + 1}\n')
				first_group = True
				first_empty_group = True
				
				for group_index, group_list in enumerate(set_list):
					if len(group_list) == 0:
						if first_empty_group:
							outfile.write(f'\t\t')
							first_empty_group = False
						
						outfile.write(f'{{}}, ')
						first_group = True
						continue
					
					if first_group:
						outfile.write('\n')
						first_group = False
					
					first_empty_group = True
					outfile.write(f'\t\t{{ // Group {group_index} - {props.GROUP_NAMES[group_index]}\n')
					# print(group_list)
					
					for prop_index, prop_list in enumerate(group_list):
						# outfile.write(f'\t\t\t\t/*  */ {{{prop_list}}},\n')
						outfile.write(f'\t\t\t/* {self.prop_names[(set_index + 1, group_index, prop_index + 1)]} */ {{{prop_list}}},\n')
						pass
					
					outfile.write('\t\t},\n')
				
				outfile.write('\t},\n')
			outfile.write('};')
	
	pass


if __name__ == '__main__':
	Main()
	pass
